---
jaeger_version: "2.14.0"
jaeger_container_name: "jaeger"
jaeger_config_dir: "/opt/jaeger"
jaeger_docker_network: "host"
# prometheus_endpoint: "http://172.17.0.1:9090"
prometheus_endpoint: "http://localhost:9090"
jaeger_memory_max_traces: 100000
jaeger_log_level: "info"

jaeger_ports:
  - "4317:4317"
  - "4318:4318"
  - "5775:5775/udp"
  - "6831:6831/udp"
  - "6832:6832/udp"
  - "5778:5778"
  - "16686:16686"
  - "14268:14268"
  - "14250:14250"
  - "9411:9411"
  - "8889:8889"
  - "8888:8888"

spanmetrics_histogram_buckets:
  - "2ms"
  - "4ms"
  - "6ms"
  - "8ms"
  - "10ms"
  - "50ms"
  - "100ms"
  - "200ms"
  - "400ms"
  - "800ms"
  - "1s"
  - "1400ms"
  - "2s"
  - "5s"
  - "10s"
  - "15s"
