---
# Prometheus Configuration
prometheus_version: "2.48.0"
prometheus_port: 9090
prometheus_data_dir: /var/lib/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_retention: "15d"

# Grafana Configuration
grafana_version: "10.2.3"
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: "admin"  # CHANGE THIS in production

# Grafana dashboards
grafana_dashboards:
  - id: 1860
    revision: 37
    name: node-exporter-full
  - id: 9628
    revision: 3
    name: postgresql-database


# Loki Configuration
loki_version: "2.9.3"
loki_port: 3100
loki_data_dir: /var/lib/loki

# Promtail Configuration
promtail_version: "2.9.3"
promtail_port: 9080

# Node Exporter Configuration
node_exporter_version: "1.7.0"
node_exporter_port: 9100

# Jaeger Configuration
jaeger_version: "1.54.0"
jaeger_http_port: 16686
jaeger_otlp_grpc_port: 4317
jaeger_otlp_http_port: 4318

# PostgreSQL Configuration
postgres_version: "15"
postgres_password: "qwerty123"
postgres_db: "expressdb"
postgres_user: "postgres"
postgres_listen_addresses: "localhost"


# Promtail Configuration
loki_url: "http://localhost:3100/loki/api/v1/push"

# Nginx Configuration
nginx_proxy_pass: "http://localhost:3000"
nginx_server_name: "_"
